from typing import Any
from robotlibcore import DynamicCore

class SwagLabsLibrary(DynamicCore):
    
    def __init__(self, is_headless: bool = True, env: str = 'prod'):...
    def open_swaglabs_in_browser(self, is_headless: bool = None, browser: str = 'chrome'):...
    def close_all_swaglabs_browser(self):...
    def reload_swaglabs_browser(self):...
    def wait_until_login_page_is_visible(self, timeout: Any = None):...
    def login_to_swaglabs(self, username: str = None, password: str = None):...
    def logout_from_swaglabs(self):...
    def menu_items_should_have(self, *args):...
    def wait_until_products_page_is_visible(self, timeout: Any = None):...
    